### ISSUE TITLE
TypeError: xarray.backends.api.open_dataset() got multiple values for keyword argument 'decode_times'

### ISSUE THREAD

**Issue by chengzhuzhang** [XCDAT/xcdat#138]
I'm not sure if it's my mis-use:

`ds = xcdat.open_dataset(demo_file, decode_times=True)`
gives:
`TypeError: xarray.backends.api.open_dataset() got multiple values for keyword argument 'decode_times'`
Demo data at:https://web.lcrc.anl.gov/public/e3sm/e3sm_diags_test_data/time-series/E3SM_v1/TS_185001_201312.nc

**Comment by tomvothecoder** [comment]
You don't need to pass the `decode_times` kwarg because it is handled by `xcdat.open_dataset()`.

`decode_times` is set to `False` so that `xcdat.dataset.decode_times()` can check whether the time units are CF-compliant or not.

https://github.com/XCDAT/xcdat/blob/d73d910fca373f52dc45c13f636e84482079035d/xcdat/dataset.py#L74-L78

If CF-compliant, call `xr.decode_cf(dataset, decode_times=True)`, which is equivalent to `xr.open_dataset("path/to/file.nc", decode_times=True)`. If not CF-compliant, then perform the manual decoding.

https://github.com/XCDAT/xcdat/blob/d73d910fca373f52dc45c13f636e84482079035d/xcdat/dataset.py#L319-L345

**Comment by chengzhuzhang** [comment]
Got it! It actually was my misuse. Thank you for clarifying. I'm closing the issue.
