### ISSUE TITLE
[Feature]: Add vertical regridding

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#45]
Blocked by #71 

### Describe the solution you'd like

Vertical regridder that can remap hybrid vertical coordinates to standard pressure levels

Acceptance criteria:

- [ ] Remapping to z-levels
- [ ] Add more....

### Additional context

[cdms](https://github.com/CDAT/cdutil/blob/master/cdutil/vertical.py#L8) has reconstructPressureFromHybrid, logLinearInterpolation, and linearInterpolation

**Comment by chengzhuzhang** [comment]
I came across [this script ](https://github.com/NCAR/geocat-comp/blob/0263d2d77ab22a6be4d1d3f16d5bfcfc68057364/src/geocat/comp/interp_hybrid_to_pressure.py)that we may be able to refer to..

**Comment by durack1** [comment]
@tomvothecoder @chengzhuzhang the xgcm code base (also xarray) could be a useful reference, see https://xgcm.readthedocs.io/en/latest/transform.html

**Comment by chengzhuzhang** [comment]
@durack1 Thank you for the reference.

**Comment by tomvothecoder** [comment]
Meeting Notes (7/20):

* Alternative solution: Ryan Abernathey mentioned vertical regridding is available in [xgcm](https://xgcm.readthedocs.io/en/latest/transform.html)
	* Maybe we can try to give this a go before implementing it ourselves?
* Otherwise, added this item for potential implementation for v1.0.0 depending on the complexity 
	* Add a feature specification doc
	* Jason and Jill work on this together?

**Comment by chengzhuzhang** [comment]
@tomvothecoder Thank you for summarizing and updating this issue. I added CDAT's vertical regridding code as a reference. 

Just a note here that the GeoCAT solution actually calls the interpolate from metpy package to actually do the vertical remapping. By a brief examination, I think both solutions should meet our requirements. And perhaps performance and use APIs will be two aspect we should focus on.

**Comment by chengzhuzhang** [comment]
@jasonb5 Hey, Jason. I spent some time to experiment with the existing vertical regridding methods. Please see the jupyter notebook here: https://github.com/xCDAT/xcdat_test/blob/main/validation/v1.0.0/vertical_interp/Vertical_interp.ipynb

Notice that only xgcm method (the third one in the notebook) is working. And I have hard time to trouble shooting the first two methods. When you have time, would you please also take a look for me. Let me know if you'd like any clarification on this. Thank you!

**Comment by jasonb5** [comment]
@chengzhuzhang Thanks, I'll give it a look over.

**Comment by chengzhuzhang** [comment]
Hey @jasonb5 , as discussed I added a 4th method, which is to use the cdms2/cdutil approach. The note book now is updated. https://github.com/xCDAT/xcdat_test/blob/main/validation/v1.0.0/vertical_interp/Vertical_interp.ipynb Thank you for looking over!

**Comment by pochedls** [comment]
Hi @jasonb5 – this looks great!

Adding a few comments based on a minimal atmospheric example (code below for reference):

* I notice that the `target_lev` dataset that I create needs to include the coordinate `lev`, though standard pressure level data is typically named `plev`. Would it be hard to give user control over the name of the level name (perhaps later as an improvement)? Or should the user just rename this after regridding?
* Note the `FutureWarning` – should the syntax `Grid.transform` be implemented now (I didn't actually look at the code to see if this comment makes sense or not – this is based only off the warming)
* Is it easy to get rid of the logger warning about missing latitude units (by solving the underlying issue)? Why is this happening for latitude and not longitude? 
* Can the method options be added to the docstring or would this be problematic (maybe this is actually a xgcm option)? If this is easy to add and isn't bad practice, it would be helpful to add it. 
* Does the xgcm method have a docstring that you can link to from `ds.regridder.vertical`? You do this for `ds.regridder.horizontal` (pointing to `xcdat.regridder.xesmf.XESMFRegridder`, for example). I'm curious what `theta` is in the docstring example (maybe this addresses my first comment?). 
* The output units on the regridded dataset are incorrect. The minimal example below doesn't provide enough information to add the units, so this makes sense, but it seems like the output units / attributes for `lev` should be pulled from the target dataset rather than copied from the source dataset. It could be good to address this.
* Suggestion for an API Change (for consideration / comment):
    * This comment is based on the behavior from CDAT, which [accepts a list of target levels](https://github.com/CDAT/cdutil/blob/master/cdutil/vertical.py#L52). Could the `target_grid` (called `output_grid` in the docstring) be either a List, Dataset, or String? I'm envisioning the following behavior: 
        * **If a dataset** – keep the core logic the same (except copy the level attributes to the output dataset); 
        * **If a List** – generate a target dataset, which can then be used for vertical regridding (output level attributes would be largely un-populated since they are not specified); 
        * **If a String** (either `standard_atmosphere` or `standard_ocean`): create a standard target dataset (with appropriate attributes, e.g., axis, units, name, etc.), which is then used for vertical regridding. 

### Simple example code

```python
import xcdat as xc
import numpy as np

fn = '/p/css03/esgf_publish/CMIP6/CMIP/MPI-M/MPI-ESM1-2-HR/historical/r8i1p1f1/CFmon/ta/gn/v20190710/*.nc'
ds = xc.open_mfdataset(fn)
p = ds.ap + ds.b*ds.ps
target_lev = xc.create_grid(lev=np.linspace(100000, 1, 13))

ds_regrid = ds.regridder.vertical("ta", target_lev, method="log", target_data=p)
```

> /../xgcm/grid.py:987: FutureWarning: From version 0.8.0 the Axis computation methods will be removed, in favour of using the Grid computation methods instead. i.e. use `Grid.transform` instead of `Axis.transform`
>   warnings.warn(
> 2023-04-18 14:09:52,753 [WARNING]: bounds.py(_create_bounds:398) >> The 'lat' coordinate variable is missing a 'units' attribute. Assuming 'units' is 'degrees_north'.

### Example output

```
ds_regrid.lev
```
> <xarray.DataArray 'lev' (lev: 13)>
> array([1.000000e+05, 9.166675e+04, 8.333350e+04, 7.500025e+04, 6.666700e+04,
>        5.833375e+04, 5.000050e+04, 4.166725e+04, 3.333400e+04, 2.500075e+04,
>        1.666750e+04, 8.334250e+03, 1.000000e+00])
> Coordinates:
>   * lev      (lev) float64 1e+05 9.167e+04 8.333e+04 ... 1.667e+04 8.334e+03 1.0
> Attributes:
>     bounds:         lev_bnds
>     units:          1
>     axis:           Z
>     positive:       down
>     long_name:      hybrid sigma pressure coordinate
>     standard_name:  atmosphere_hybrid_sigma_pressure_coordinate
>     formula:        p = ap + b*ps
>     formula_terms:  ap: ap b: b ps: ps

Tagging @mzelinka / @chengzhuzhang – to see if they have comments on my suggestions / comments.
